<script>
	$(document).ready(function () {

		$(".dettaglio").click(function () {

			window.location = 'dettaglio?id=' + $(this).attr("value");
		});
	});

</script>


<div class="row  filmjumbo">



	<div class="col-xs-12 col-md-4 col-lg-3">
		<div class="col-xs-12 col-md-12 col-lg-12 jumbotron contentjumbo">
			<div class="carousel-inner">

				<div id="imageFilmDiv">
					<img src="http://localhost/cinema/image/MOLLYSGAME.jpg" style="min-width:100%;" class="imgfilm">



				</div>
			</div>
		</div>
	</div>




	<div class="col-xs-12 col-md-4 col-lg-5 " style="word-wrap:break-word;">
		<div class="col-xs-10 col-md-12 col-lg-12    ">

			<div>
				<div>
					<p class=" " align="center ">
						TITOLONEEEE

					</p>
				</div>
				<br>
				<br>
				<div class="col-xs-3 col-md-3 col-lg-3 ">
					<p>
						DATONAAAA
					</p>
				</div>
				<div class="col-xs-3 col-md-3 col-lg-3 ">

				</div>
				<div class="col-xs-6 col-md-6 col-lg-6 ">
					<p>19.00 </p>
				</div>
				</br>
				</br>
				</br>
				<div class="row">
					<div class="col-xs-12 col-md-12 col-lg-12 ">
						<p>
							DURATA
						</p>
					</div>
				</div>
				</br>

				<div class="row">
					<div class="col-xs-12 col-md-12 col-lg-12 ">
						<p>
							ANOANOANOANAONAONAONAOANOANOANOANOAONOANOANONOANOANOAONOANOAONOANOAOANOANAONAONAOOANONAONAOANOAONAOANONAOANANAONAOOANNONAN
						</p>
					</div>
				</div>

				<div class="row">

				</div>
				<div class="row">
					<div class="col-xs-12 col-md-12 col-lg-12 ">
						<p>
							quualcosaltrooo
						</p>
					</div>
				</div>
				</br>

				<div class="row">
					<div class="col-xs-12 col-md-12 col-lg-12 ">
						<p>
							ANOANOANOANAONAONAONAOANOANOANOANOAONOANOANONOANOANOAONOANOAONOANOAOANOANAONAONAOOANONAONAOANOAONAOANONAOANANAONAOOANNONAN
						</p>
					</div>
				</div>


				<div class="row">
					<div class="col-xs-12 col-md-12 col-lg-12 ">
						<p>
							descriziononeeeeeeeeee
						</p>
					</div>
				</div>
				</br>

				<div class="row">
					<div class="col-xs-12 col-md-12 col-lg-12 ">
						<p>
							ANOANOANOANAONAONAONAOANOANOANOANOAONOANOANONOANOANOONAOANOANOANOANOAONOANOANONOANOANOAONONAOANOANOANOANOAONOANOANONOANOANOAONONAOANOANOANOANOAONOANOANONOANOANOAONONAOANOANOANOANOAONOANOANONOANOANOAONONAOANOANOANOANOAONOANOANONOANOANOAONAONOANOAONOANOAOANOANAONAONAOOANONAONAOANOAONAOANONAOANANAONAOOANNONAN
						</p>
					</div>
				</div>

				<div class="row">

				</div>




			</div>

		</div>
	</div>
</div>