


<script src="http://127.0.0.1/cinema/js/feedreader.js"></script>
 <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    

  <script language="JavaScript" type="text/javascript">
  $(document).ready(function() {
$('#boxnews').feedreader({
  targeturl: 'https://rss.news.yahoo.com/rss/topstories',
  items: 3,
  descLength: 30
});
});
</script>

    </script>

<center>

</center>
<div id="boxnews"></div>
