<!DOCTYPE html>
<html>

<head>
  <!-- CSS links -->
 
  <link rel="stylesheet" href="http://127.0.0.1/cinema/css/bootstrap3.3.5/bootstrap.min.css">
  <link rel="stylesheet" href="http://127.0.0.1/cinema/css/bootstrap-datepicker.min.css">
  <link rel="stylesheet" href="http://127.0.0.1/cinema/css/stile.css">

  <script src="http://127.0.0.1/cinema/js/jquery-1.11.0.min.js"></script>
  <script src="http://127.0.0.1/cinema/js/bootstrap3.3.5/bootstrap.min.js"></script>
  <script src="http://127.0.0.1/cinema/js/bootstrap-datepicker.min.js"></script>
  <script src="http://127.0.0.1/cinema/js/bootstrap-datepicker.it.min.js"></script>

  <link rel="stylesheet" href="http://127.0.0.1/cinema/css/stile.css">

  <title>Cinema Accademia</title>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top barranav">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand links" href="#">CinemaAccademia</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <a href="#" class="links">Link</a>
          </li>
          <li>
            <a href="#" class="links">Contatti</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container-fluid" id="maincontainer">
    {{{content}}}
  </div>

  <footer class="footer">
    <h5>Via Montanelli 33, 50065 Pontassieve FI - Tel. 0558368252</h5>
  </footer>
</body>

</html>